lHost *:80>
    ServerAdmin admin@yourdomain.com
    ServerName webapptest.live
    ServerAlias www.webapptest.live
    DocumentRoot /var/www/html/webapp-QA

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    <Directory /var/www/html/webapp-QA>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

